moai:
  initialized: true
  initialized_at: '2025-12-19T00:00:00Z'
  version: 1.12.15
project:
  name: excalidraw-cli
  mode: personal
  description: ''
  created_at: '2026-01-26 20:30:15'
  optimized: false
  template_version: 1.12.15
