moai:
    initialized: true
    initialized_at: "2025-12-19T00:00:00Z"
    version: 1.14.5
project:
    created_at: "2026-01-26 20:30:15"
    description: ""
    mode: personal
    name: excalidraw-cli
    optimized: false
    template_version: ""
